workflows:
  ios_app_store:
    name: iOS App Store
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      # Create these groups in Codemagic UI and add the variables inside them
      groups:
        - supabase_env            # SUPABASE_URL, SUPABASE_ANON_KEY
        - app_store_connect       # APP_STORE_CONNECT_PRIVATE_KEY, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_ISSUER_ID
        - revenuecat_env          # REVENUECAT_IOS_PUBLIC_SDK_KEY
        - supabse                 # fallback if group was misspelled in UI
        # Optionally: ios_signing  # If you prefer manual signing (CERT, CERT_PASSWORD, PROVISIONING_PROFILE)
      vars:
        BUNDLE_ID: com.mechanicpart.mechanicPart
        XCODE_WORKSPACE: ios/Runner.xcworkspace
        XCODE_SCHEME: Runner
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
      cancel_previous_builds: true
    scripts:
      - name: Flutter version
        script: flutter --version
      - name: Dependencies
        script: flutter pub get
      - name: Create .env from CI variables
        script: |
          echo "Creating .env for Flutter asset bundling"
          {
            [ -n "${SUPABASE_URL:-}" ] && echo "SUPABASE_URL=${SUPABASE_URL}";
            [ -n "${SUPABASE_ANON_KEY:-}" ] && echo "SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}";
            [ -n "${REVENUECAT_IOS_PUBLIC_SDK_KEY:-}" ] && echo "REVENUECAT_IOS_PUBLIC_SDK_KEY=${REVENUECAT_IOS_PUBLIC_SDK_KEY}";
          } > .env
          echo ".env created"
      - name: Generate launcher icons (idempotent)
        script: dart run flutter_launcher_icons
      - name: Generate native splash (idempotent)
        script: dart run flutter_native_splash:create
      - name: Verify required env vars (Supabase)
        script: |
          if [ -z "${SUPABASE_URL:-}" ] || [ -z "${SUPABASE_ANON_KEY:-}" ]; then
            echo "Missing SUPABASE_URL or SUPABASE_ANON_KEY"
            exit 1
          fi
          echo "SUPABASE_URL is set"
          echo "SUPABASE_ANON_KEY is set"
      - name: Fetch signing files (App Store Connect)
        script: |
          set -e
          echo "Fetching signing files for $BUNDLE_ID (App Store)"
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --issuer-id $APP_STORE_CONNECT_ISSUER_ID \
            --key-id $APP_STORE_CONNECT_KEY_IDENTIFIER \
            --private-key @env:APP_STORE_CONNECT_PRIVATE_KEY
      - name: Add signing certificates to keychain
        script: |
          # Import certificates only if provided (manual signing). Codemagic Automatic
          # signing may not place .p12 files in the Certificates folder.
          CERT_DIR="$HOME/Library/MobileDevice/Certificates"
          if ls "$CERT_DIR"/*.p12 >/dev/null 2>&1 || [ -n "${CM_CERTIFICATE:-}" ]; then
            echo "Importing signing certificates from $CERT_DIR or env..."
            keychain add-certificates
          else
            echo "No .p12 certificates provided; skipping import (expecting Codemagic Automatic signing)."
          fi
      - name: Debug signing assets
        script: |
          echo "-- Code signing identities --"
          security find-identity -v -p codesigning || true
          echo "-- Provisioning profiles --"
          ls -al "$HOME/Library/MobileDevice/Provisioning Profiles" || true
      - name: Flutter build ios (no codesign)
        script: |
          flutter build ios --release --no-codesign \
            --dart-define SUPABASE_URL="$SUPABASE_URL" \
            --dart-define SUPABASE_ANON_KEY="$SUPABASE_ANON_KEY" \
            --dart-define REVENUECAT_IOS_PUBLIC_SDK_KEY="$REVENUECAT_IOS_PUBLIC_SDK_KEY"
      - name: Configure Xcode project with provisioning profiles (if available)
        script: |
          PROFILE_DIR="$HOME/Library/MobileDevice/Provisioning Profiles"
          if ls "$PROFILE_DIR"/*.mobileprovision >/dev/null 2>&1; then
            echo "Found provisioning profiles, applying with xcode-project use-profiles"
            xcode-project use-profiles
          else
            echo "No provisioning profiles found; skipping use-profiles (will use Automatic signing)."
          fi
      - name: Show Xcode signing build settings
        script: |
          set -e
          echo "--- Xcode Build Settings (signing-related) ---"
          xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -showBuildSettings | egrep -i "^(\s*CODE_SIGN|\s*PROVISIONING_PROFILE|\s*PRODUCT_BUNDLE_IDENTIFIER|\s*DEVELOPMENT_TEAM)"
      - name: Archive and Export IPA with xcodebuild (Automatic signing)
        script: |
          # Strip injected export options envs and always provide our own file
          unset CM_EXPORT_OPTIONS || true
          unset EXPORT_OPTIONS_PLIST || true
          FALLBACK_PLIST="$HOME/export_options.plist"
          echo "Writing export options plist to $FALLBACK_PLIST"
          printf '%s\n' \
            '<?xml version="1.0" encoding="UTF-8"?>' \
            '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">' \
            '<plist version="1.0">' \
            '<dict>' \
            '  <key>method</key>' \
            '  <string>app-store</string>' \
            '  <key>signingStyle</key>' \
            '  <string>automatic</string>' \
            '  <key>uploadBitcode</key>' \
            '  <false/>' \
            '  <key>compileBitcode</key>' \
            '  <false/>' \
            '</dict>' \
            '</plist>' > "$FALLBACK_PLIST"
          ARCHIVE_PATH="$PWD/build/ios/archive/Runner.xcarchive"
          mkdir -p "$(dirname "$ARCHIVE_PATH")" build/ios/ipa
          EXTRA_XCARGS="CODE_SIGN_STYLE=Automatic PRODUCT_BUNDLE_IDENTIFIER=$BUNDLE_ID"
          if [ -n "${APPLE_TEAM_ID:-}" ]; then EXTRA_XCARGS="$EXTRA_XCARGS DEVELOPMENT_TEAM=$APPLE_TEAM_ID"; fi
          echo "Archiving with: $EXTRA_XCARGS"
          xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -configuration Release -allowProvisioningUpdates -archivePath "$ARCHIVE_PATH" archive $EXTRA_XCARGS
          echo "Exporting IPA..."
          xcodebuild -exportArchive -archivePath "$ARCHIVE_PATH" -exportOptionsPlist "$FALLBACK_PLIST" -exportPath build/ios/ipa
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
    publishing:
      app_store_connect:
        # Provide these as secure env vars in group: app_store_connect
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        # Optional: set changelog from last commit
        # changelog: "$CM_COMMIT_MESSAGE"

