workflows:
  ios_app_store:
    name: iOS App Store
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      # Create these groups in Codemagic UI and add the variables inside them
      groups:
        - supabase_env            # SUPABASE_URL, SUPABASE_ANON_KEY
        - app_store_connect       # APP_STORE_CONNECT_PRIVATE_KEY, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_ISSUER_ID
        - revenuecat_env          # REVENUECAT_IOS_PUBLIC_SDK_KEY
        - supabse                 # fallback if group was misspelled in UI
        # Optionally: ios_signing  # If you prefer manual signing (CERT, CERT_PASSWORD, PROVISIONING_PROFILE)
      vars:
        BUNDLE_ID: com.mechanicpart.mechanicPart
        XCODE_WORKSPACE: ios/Runner.xcworkspace
        XCODE_SCHEME: Runner
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
      cancel_previous_builds: true
    scripts:
      - name: Flutter version
        script: flutter --version
      - name: Dependencies
        script: flutter pub get
      - name: Create .env from CI variables
        script: |
          echo "Creating .env for Flutter asset bundling"
          {
            [ -n "${SUPABASE_URL:-}" ] && echo "SUPABASE_URL=${SUPABASE_URL}";
            [ -n "${SUPABASE_ANON_KEY:-}" ] && echo "SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}";
            [ -n "${REVENUECAT_IOS_PUBLIC_SDK_KEY:-}" ] && echo "REVENUECAT_IOS_PUBLIC_SDK_KEY=${REVENUECAT_IOS_PUBLIC_SDK_KEY}";
          } > .env
          echo ".env created"
      - name: Generate launcher icons (idempotent)
        script: dart run flutter_launcher_icons
      - name: Generate native splash (idempotent)
        script: dart run flutter_native_splash:create
      - name: Verify required env vars (Supabase)
        script: |
          if [ -z "${SUPABASE_URL:-}" ] || [ -z "${SUPABASE_ANON_KEY:-}" ]; then
            echo "Missing SUPABASE_URL or SUPABASE_ANON_KEY"
            exit 1
          fi
          echo "SUPABASE_URL is set"
          echo "SUPABASE_ANON_KEY is set"
      # Manual signing path: upload P12 and provisioning profile in Codemagic UI
      - name: Add signing certificates to keychain
        script: |
          # Import certificates and provisioning profiles managed by Codemagic
          set +e
          keychain add-certificates
          STATUS=$?
          echo "keychain add-certificates exit code: $STATUS"
          set -e || true
          # Never fail this step; continue to fallback/import and use-profiles
          true
      - name: "Fallback: install signing assets from env (if provided)"
        script: |
          set -e
          CERT_TMP="$HOME/certificate.p12"
          PROFILE_DIR="$HOME/Library/MobileDevice/Provisioning Profiles"
          mkdir -p "$PROFILE_DIR"
          if [ -n "${IOS_CERTIFICATE_P12:-}" ] && [ -n "${IOS_CERTIFICATE_PASSWORD:-}" ]; then
            echo "Decoding IOS_CERTIFICATE_P12 from env"
            echo "$IOS_CERTIFICATE_P12" | base64 --decode > "$CERT_TMP"
            security import "$CERT_TMP" -k "$HOME/Library/Keychains/login.keychain-db" -P "$IOS_CERTIFICATE_PASSWORD" -T /usr/bin/codesign -T /usr/bin/security || true
            rm -f "$CERT_TMP"
          fi
          if [ -n "${IOS_PROVISIONING_PROFILE:-}" ]; then
            echo "Decoding IOS_PROVISIONING_PROFILE from env"
            echo "$IOS_PROVISIONING_PROFILE" | base64 --decode > "$PROFILE_DIR/Manual.mobileprovision"
          fi
      - name: Debug signing assets
        script: |
          echo "-- Code signing identities --"
          security find-identity -v -p codesigning || true
          echo "-- Provisioning profiles --"
          ls -al "$HOME/Library/MobileDevice/Provisioning Profiles" || true
      - name: Flutter build ios (no codesign)
        script: |
          flutter build ios --release --no-codesign \
            --dart-define SUPABASE_URL="$SUPABASE_URL" \
            --dart-define SUPABASE_ANON_KEY="$SUPABASE_ANON_KEY" \
            --dart-define REVENUECAT_IOS_PUBLIC_SDK_KEY="$REVENUECAT_IOS_PUBLIC_SDK_KEY"
      - name: Configure Xcode project with provisioning profiles
        script: |
          xcode-project use-profiles
      - name: Resolve provisioning profile UUID (force)
        script: |
          set -e
          PROFILE_DIR="$HOME/Library/MobileDevice/Provisioning Profiles"
          MATCH_NAME=""
          MATCH_UUID=""
          for p in "$PROFILE_DIR"/*.mobileprovision; do
            [ -f "$p" ] || continue
            INFO=$(security cms -D -i "$p" 2>/dev/null || true)
            NAME=$(/usr/libexec/PlistBuddy -c 'Print :Name' /dev/stdin <<< "$INFO" 2>/dev/null || true)
            UUID=$(/usr/libexec/PlistBuddy -c 'Print :UUID' /dev/stdin <<< "$INFO" 2>/dev/null || true)
            APP_ID=$(/usr/libexec/PlistBuddy -c 'Print :Entitlements:application-identifier' /dev/stdin <<< "$INFO" 2>/dev/null || true)
            if [ -n "$APP_ID" ]; then
              if [[ "$APP_ID" == "${APPLE_TEAM_ID:-}.$BUNDLE_ID" || "$APP_ID" == *".$BUNDLE_ID" ]]; then
                MATCH_NAME="$NAME"
                MATCH_UUID="$UUID"
                echo "Matched provisioning profile: name='$MATCH_NAME' uuid='$MATCH_UUID' for $APP_ID"
                break
              fi
            fi
          done
          if [ -z "$MATCH_UUID" ]; then
            echo "ERROR: No provisioning profile found for $BUNDLE_ID in $PROFILE_DIR. Upload an App Store profile or set IOS_PROVISIONING_PROFILE env."
            exit 1
          fi
          export PROFILE_UUID="$MATCH_UUID"
          export PROFILE_NAME="$MATCH_NAME"
          export PROFILE_SPECIFIER="$MATCH_NAME"
          if [ -n "${CM_ENV:-}" ]; then
            echo "PROFILE_UUID=$PROFILE_UUID" >> "$CM_ENV"
            echo "PROFILE_NAME=$PROFILE_NAME" >> "$CM_ENV"
            echo "PROFILE_SPECIFIER=$PROFILE_SPECIFIER" >> "$CM_ENV"
          fi
      - name: Show Xcode signing build settings
        script: |
          set -e
          echo "--- Xcode Build Settings (signing-related) ---"
          xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -configuration Release -sdk iphoneos -destination "generic/platform=iOS" -showBuildSettings | egrep -i "^(\s*CODE_SIGN|\s*PROVISIONING_PROFILE|\s*PRODUCT_BUNDLE_IDENTIFIER|\s*DEVELOPMENT_TEAM)"
      - name: Build IPA with Xcode (manual signing, UUID)
        script: |
          # Strip injected export options envs and always provide our own file
          unset CM_EXPORT_OPTIONS || true
          unset EXPORT_OPTIONS_PLIST || true
          FALLBACK_PLIST="$HOME/export_options.plist"
          echo "Writing export options plist to $FALLBACK_PLIST"
          # Require UUID and map export to the profile name
          if [ -z "${PROFILE_UUID:-}" ]; then
            echo "ERROR: PROFILE_UUID is not set; cannot proceed with manual signing."
            exit 1
          fi
          EXPORT_NAME="${PROFILE_NAME:-${PROFILE_SPECIFIER:-AppStoreProfile}}"
          printf '%s\n' \
            '<?xml version="1.0" encoding="UTF-8"?>' \
            '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">' \
            '<plist version="1.0">' \
            '<dict>' \
            '  <key>method</key>' \
            '  <string>app-store</string>' \
            '  <key>signingStyle</key>' \
            '  <string>manual</string>' \
            '  <key>provisioningProfiles</key>' \
            '  <dict>' \
            "    <key>$BUNDLE_ID</key>" \
            "    <string>$EXPORT_NAME</string>" \
            '  </dict>' \
            '  <key>uploadBitcode</key>' \
            '  <false/>' \
            '  <key>compileBitcode</key>' \
            '  <false/>' \
            '</dict>' \
            '</plist>' > "$FALLBACK_PLIST"
          XCARGS="CODE_SIGN_STYLE=Manual PROVISIONING_PROFILE=$PROFILE_UUID PRODUCT_BUNDLE_IDENTIFIER=$BUNDLE_ID"
          if [ -n "${APPLE_TEAM_ID:-}" ]; then XCARGS="$XCARGS DEVELOPMENT_TEAM=$APPLE_TEAM_ID"; fi
          env -u CM_EXPORT_OPTIONS -u EXPORT_OPTIONS_PLIST \
            xcode-project build-ipa \
              --workspace "$XCODE_WORKSPACE" \
              --scheme "$XCODE_SCHEME" \
              --archive-flags="-allowProvisioningUpdates" \
              --archive-xcargs "$XCARGS" \
              --export-options-plist "$FALLBACK_PLIST"
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
    publishing:
      app_store_connect:
        # Provide these as secure env vars in group: app_store_connect
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        # Optional: set changelog from last commit
        # changelog: "$CM_COMMIT_MESSAGE"

